@echo off
echo Starting Pegasus Spare Counting App...
echo Checking for node_modules...

if not exist "node_modules\" (
    echo node_modules not found. Installing dependencies...
    call npm install
)

echo Starting Vite development server...
call npm run dev
pause
